name: Build and deploy Node.js app to Azure Web App - maoamiga

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Create deployment package
        run: |
          Compress-Archive -Path ./dist -DestinationPath deployment-package.zip
        working-directory: ${{ github.workspace }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: deployment-package
          path: deployment-package.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: deployment-package

      - name: Unzip artifact for deployment
        run: Expand-Archive -Path deployment-package.zip -DestinationPath . -Force

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'maoamiga'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist
